const STANDARD_DESIGNS = [
  {
    id: "actual",
    name: "Diseño actual de Parchar",
    note: "Conserva exactamente los botones e iconos actuales de Parchar.",
    pageStart: "#2a1050",
    pageEnd: "#10071f",
    shellStart: "#48217d",
    shellEnd: "#1c0a39",
    accent: "#ffcc58",
    text: "#fff8ff",
    softText: "#d8c5ed",
    line: "#bb7aff",
    iconMode: "actual",
    layout: "original",
  },
  {
    id: "clasico-luminoso",
    name: "Navidad brillante",
    note: "Arbolitos ilustrados, guirnaldas de luces y bordes festivos en los botones.",
    pageStart: "#34105c",
    pageEnd: "#17072b",
    shellStart: "#552391",
    shellEnd: "#281047",
    accent: "#ffd052",
    text: "#fff9ff",
    softText: "#e5cff4",
    line: "#d277ff",
    iconMode: "line",
    layout: "glass-squares",
  },
  {
    id: "feria-flores",
    name: "Feria de las Flores",
    note: "Flores de colores, guirnaldas y detalles inspirados en las silletas de Medellín.",
    pageStart: "#35105c",
    pageEnd: "#19092c",
    shellStart: "#642184",
    shellEnd: "#321047",
    accent: "#ffe15a",
    text: "#fff9ff",
    softText: "#f1d8f3",
    line: "#f58bd4",
    iconMode: "line",
    layout: "glass-squares",
  },
  {
    id: "violeta",
    name: "Grafito elegante",
    note: "Botones grafito redondeados con iconos claros y acabado metálico.",
    pageStart: "#31105a",
    pageEnd: "#180830",
    shellStart: "#54248b",
    shellEnd: "#2d1250",
    accent: "#ffca58",
    text: "#fbf7ff",
    softText: "#d1c2df",
    line: "#c06dff",
    iconMode: "line",
    layout: "squircle",
  },
  {
    id: "noche",
    name: "Círculos cromados",
    note: "Botones circulares con brillo metálico e iconos centrados.",
    pageStart: "#191b55",
    pageEnd: "#11102f",
    shellStart: "#292b79",
    shellEnd: "#1d1b54",
    accent: "#42dcff",
    text: "#f8f8ff",
    softText: "#c8d8ff",
    line: "#7778ff",
    iconMode: "line",
    layout: "chrome-circles",
  },
  {
    id: "natural",
    name: "Aqua brillante",
    note: "Botones circulares color aqua, relucientes y fáciles de reconocer.",
    pageStart: "#0b4b40",
    pageEnd: "#082a27",
    shellStart: "#12705c",
    shellEnd: "#104b43",
    accent: "#ffd44d",
    text: "#f5fbf7",
    softText: "#c1d9d0",
    line: "#56dfb0",
    iconMode: "line",
    layout: "aqua-circles",
  },
  {
    id: "claro",
    name: "Neón contorneado",
    note: "Botones cuadrados con bordes luminosos rosa, cian y dorado.",
    pageStart: "#fff0fb",
    pageEnd: "#eadfff",
    shellStart: "#ffffff",
    shellEnd: "#f8efff",
    accent: "#813dd2",
    text: "#28153c",
    softText: "#59456c",
    line: "#c294ee",
    iconMode: "line",
    layout: "neon-outline",
  },
  {
    id: "coral",
    name: "Píldoras a color",
    note: "Botones alargados con icono y nombre juntos en una sola pieza.",
    pageStart: "#471338",
    pageEnd: "#220e29",
    shellStart: "#82245e",
    shellEnd: "#44173d",
    accent: "#ff8c56",
    text: "#fff8fc",
    softText: "#f0cce5",
    line: "#f17bb3",
    iconMode: "line",
    layout: "pills",
  },
];

const STANDARD_DESIGN_BY_ID = new Map(
  STANDARD_DESIGNS.map((design) => [design.id, design]),
);

function normalizeStandardDesignId(value) {
  if (value === "clasico") return "actual";
  return STANDARD_DESIGN_BY_ID.has(value) ? value : "actual";
}

function getStandardDesign(value = "actual") {
  return STANDARD_DESIGN_BY_ID.get(normalizeStandardDesignId(value));
}

module.exports = {
  STANDARD_DESIGNS,
  getStandardDesign,
  normalizeStandardDesignId,
};
